### ISSUE TITLE
need to better support refactoring/changing code

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#440]
steps: 
* updating ent-rsvp backend to use `defaultToViewerOnCreate` which was introduced in https://github.com/lolopinto/ent/pull/437
* change schema as follows:
```diff
ola@OlaspersonalMBP backend % git diff src/schema/
diff --git a/examples/ent-rsvp/backend/src/schema/event.ts b/examples/ent-rsvp/backend/src/schema/event.ts
index 96983805..21813231 100644
--- a/examples/ent-rsvp/backend/src/schema/event.ts
+++ b/examples/ent-rsvp/backend/src/schema/event.ts
@@ -15,12 +15,14 @@ export default class Event extends BaseEntSchema {
     UUIDType({
       name: "creatorID",
       foreignKey: { schema: "User", column: "ID" },
+      defaultToViewerOnCreate: true,
     }),
   ];
 
   actions: Action[] = [
     {
       operation: ActionOperation.Create,
+      fields: ["Name", "Slug"],
       actionOnlyFields: [
         {
           name: "activities",

```

and then run `tsent codegen` 

and this error is seen:

```shell
ola@OlaspersonalMBP backend % tsent codegen
checking for custom graphql definitions...
updating db...
schema is up to date
generating ent code...
generating graphql code...

/usr/local/lib/node_modules/ts-node/src/index.ts:500
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/ent/event/actions/create_event_action.ts:23:48 - error TS2339: Property 'creatorID' does not exist on type 'EventCreateInput'.

23         new AllowIfViewerEqualsRule(this.input.creatorID),
                                                  ~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
Error: error writing schema file: exit status 1
Usage:
  tsent codegen [flags]

Flags:
      --debug         debug mode. add debug information to codegen e.g. files written etc
  -h, --help          help for codegen
  -s, --step string   limit to only run a particular step e.g. db, graphql, codegen

error writing schema file: exit status 1
```

ideally, this error is ignored and the codegen happens and user is pointed to changes that need to be made after.

this was at https://github.com/lolopinto/ent/commit/28e3ab2b21dc28cd967ddb68e966e35331ba6c93
